/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nlppreprocessing;

/**
 *
 * @author HaithamGamal
 */
public class Choose extends javax.swing.JFrame {

    /**
     * Creates new form Choose
     */
    public Choose() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tokiniz = new javax.swing.JCheckBox();
        lemit = new javax.swing.JCheckBox();
        stop = new javax.swing.JCheckBox();
        stemming = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        begin = new javax.swing.JButton();
        POS = new javax.swing.JCheckBox();
        LEM = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText(" Please Choose The Operation");

        tokiniz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tokiniz.setForeground(new java.awt.Color(255, 102, 0));
        tokiniz.setText("Tokinization");
        tokiniz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokinizActionPerformed(evt);
            }
        });

        lemit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lemit.setForeground(new java.awt.Color(255, 102, 0));
        lemit.setText("Lemitization");

        stop.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stop.setForeground(new java.awt.Color(255, 102, 0));
        stop.setText("Stopping");

        stemming.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stemming.setForeground(new java.awt.Color(255, 102, 0));
        stemming.setText("Stemming");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));

        begin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        begin.setForeground(new java.awt.Color(255, 0, 0));
        begin.setText("Begin");
        begin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginActionPerformed(evt);
            }
        });

        POS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        POS.setForeground(new java.awt.Color(255, 102, 0));
        POS.setText("POS");

        LEM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LEM.setForeground(new java.awt.Color(255, 102, 0));
        LEM.setText("LEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tokiniz)
                            .addComponent(lemit)
                            .addComponent(stop)
                            .addComponent(stemming)
                            .addComponent(POS)
                            .addComponent(LEM)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(begin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LEM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(lemit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tokiniz)
                        .addGap(31, 31, 31)))
                .addComponent(stop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stemming)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(POS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(begin)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tokinizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokinizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokinizActionPerformed

    private void beginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginActionPerformed
        // TODO add your handling code here:
        if (tokiniz.isSelected() && stop.isSelected()) {
            Stop st = new Stop();
            st.setVisible(true);
            setVisible(false);

        } else if (tokiniz.isSelected() && stemming.isSelected()) {
            Stem stm = new Stem();
            stm.setVisible(true);
            setVisible(false);
        } else if (tokiniz.isSelected()) {
            StartTokenizeTwo tk = new StartTokenizeTwo();
            tk.setVisible(true);
            setVisible(false);
        } else if (POS.isSelected()) {
            POS pos = new POS();
            pos.setVisible(true);
            setVisible(false);

        } else if (LEM.isSelected()) {

            LEM lem = new LEM();
            lem.setVisible(true);
            setVisible(false);
        }


    }//GEN-LAST:event_beginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox LEM;
    private javax.swing.JCheckBox POS;
    private javax.swing.JButton begin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox lemit;
    private javax.swing.JCheckBox stemming;
    private javax.swing.JCheckBox stop;
    private javax.swing.JCheckBox tokiniz;
    // End of variables declaration//GEN-END:variables
}
