/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nlppreprocessing;

import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HaithamGamal
 */
public class StartTokenizeTwo extends javax.swing.JFrame {

    /**
     * Creates new form StartTokenizeTwo
     */
    public StartTokenizeTwo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        senten = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        tok = new javax.swing.JButton();
        filenam = new javax.swing.JTextField();
        shup = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultfile = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        readfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Type Your Sentence");

        senten.setColumns(20);
        senten.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        senten.setForeground(new java.awt.Color(255, 0, 0));
        senten.setRows(5);
        jScrollPane1.setViewportView(senten);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Result");

        result.setColumns(20);
        result.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        result.setForeground(new java.awt.Color(255, 0, 0));
        result.setRows(5);
        jScrollPane2.setViewportView(result);

        tok.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tok.setForeground(new java.awt.Color(255, 102, 0));
        tok.setText("Tokinize");
        tok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokActionPerformed(evt);
            }
        });

        filenam.setForeground(new java.awt.Color(255, 0, 0));
        filenam.setEnabled(false);

        shup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shup.setForeground(new java.awt.Color(255, 102, 0));
        shup.setText("Show Upload");
        shup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shupActionPerformed(evt);
            }
        });

        resultfile.setColumns(20);
        resultfile.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        resultfile.setForeground(new java.awt.Color(255, 0, 0));
        resultfile.setRows(5);
        jScrollPane3.setViewportView(resultfile);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Result");

        readfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        readfile.setForeground(new java.awt.Color(255, 102, 0));
        readfile.setText("ReadFile and Print Result");
        readfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(tok, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(shup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(readfile)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filenam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tok)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shup)
                    .addComponent(filenam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(readfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("RedundantStringToString")
    private void tokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokActionPerformed
        // TODO add your handling code here:
        LinkedList<String> fileData =new LinkedList<String>();
         LinkedList<String[]> dataAfterTokinization2=new LinkedList<String[]>();
        try {
            dataAfterTokinization2= new FileOperations(null).readSentenceFromTheUser(senten.getText().toString(), fileData);//where null is the filename
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StartTokenizeTwo.class.getName()).log(Level.SEVERE, null, ex);
        }
       try{for (int i = 0; i <dataAfterTokinization2.size(); i++) {
            for (int j = 0; j <  dataAfterTokinization2.get(i).length; j++) {
                //System.out.println( dataAfterTokinization2.get(i)[j]);
                System.out.println(dataAfterTokinization2.get(i)[j]);
                result.append(" \n"+" "+dataAfterTokinization2.get(i)[j]);
               
               
                
                
            }
       }
        
       }
       catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_tokActionPerformed

    private void shupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shupActionPerformed
        // TODO add your handling code here:
        filenam.setEnabled(true);
        
    }//GEN-LAST:event_shupActionPerformed

    private void readfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readfileActionPerformed
        // TODO add your handling code here:
         LinkedList<String> fileData =new LinkedList<String>();
         LinkedList<String[]> dataAfterTokinization2=new LinkedList<String[]>();
        try {
            dataAfterTokinization2= new FileOperations("DataRead.txt").readSentenceFromTheUser(null, fileData);//where null is the filename
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StartTokenizeTwo.class.getName()).log(Level.SEVERE, null, ex);
        }
       try{for (int i = 0; i <dataAfterTokinization2.size(); i++) {
            for (int j = 0; j <  dataAfterTokinization2.get(i).length; j++) {
                //System.out.println( dataAfterTokinization2.get(i)[j]);
                System.out.println(dataAfterTokinization2.get(i)[j]);
                resultfile.append("\n "+dataAfterTokinization2.get(i)[j]);
               
               
                
                
            }
       }
        
       }
       catch(Exception e){
           System.out.println(e);
       }
        
    }//GEN-LAST:event_readfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartTokenizeTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartTokenizeTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartTokenizeTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartTokenizeTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartTokenizeTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filenam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton readfile;
    private javax.swing.JTextArea result;
    private javax.swing.JTextArea resultfile;
    private javax.swing.JTextArea senten;
    private javax.swing.JButton shup;
    private javax.swing.JButton tok;
    // End of variables declaration//GEN-END:variables
}
