/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nlppreprocessing;

import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HaithamGamal
 */
public class Stop extends javax.swing.JFrame {

    /**
     * Creates new form Stop
     */
    public Stop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sentstop = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultstop = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        stop = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        upload = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txrdupld = new javax.swing.JTextArea();
        rdup = new javax.swing.JButton();
        shupload = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sentstop.setColumns(20);
        sentstop.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        sentstop.setForeground(new java.awt.Color(255, 0, 0));
        sentstop.setRows(5);
        jScrollPane1.setViewportView(sentstop);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Type Your Sentence");

        resultstop.setColumns(20);
        resultstop.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        resultstop.setForeground(new java.awt.Color(255, 0, 0));
        resultstop.setRows(5);
        jScrollPane2.setViewportView(resultstop);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Result");

        stop.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stop.setForeground(new java.awt.Color(255, 102, 0));
        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        upload.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        upload.setForeground(new java.awt.Color(255, 102, 0));
        upload.setText("showUpload");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });

        txrdupld.setColumns(20);
        txrdupld.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txrdupld.setForeground(new java.awt.Color(255, 0, 0));
        txrdupld.setRows(5);
        jScrollPane3.setViewportView(txrdupld);

        rdup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdup.setForeground(new java.awt.Color(255, 102, 0));
        rdup.setText("Read And Upload");
        rdup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdupActionPerformed(evt);
            }
        });

        shupload.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shupload.setForeground(new java.awt.Color(255, 0, 0));
        shupload.setEnabled(false);
        shupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shuploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(upload)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(shupload)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(rdup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upload)
                    .addComponent(shupload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(rdup)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
          LinkedList<String> fileData =new LinkedList<String>();
         LinkedList<String[]> dataAfterTokinization2=new LinkedList<String[]>();
         LinkedList<String> stopWords=new LinkedList<String>();
        try {
            dataAfterTokinization2= new FileOperations(null).readSentenceFromTheUser(sentstop.getText().toString(), fileData);
            StopWordList st=new StopWordList("Stop.txt",stopWords);
            LinkedList<String[]> dataAfterstopOperation= st.checkStopWords(dataAfterTokinization2);
            for (int i = 0; i < dataAfterstopOperation.size(); i++) {
                for (int j = 0; j < dataAfterstopOperation.get(i).length; j++) {
                    resultstop.append(" "+dataAfterstopOperation.get(i)[j]);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Stop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stopActionPerformed

    private void rdupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdupActionPerformed
        // TODO add your handling code here:
        LinkedList<String> fileData =new LinkedList<String>();
         LinkedList<String[]> dataAfterTokinization2=new LinkedList<String[]>();
          LinkedList<String> stopWords=new LinkedList<String>();
        try {
            dataAfterTokinization2= new FileOperations(shupload.getText().toString()).readSentenceFromTheUser(null, fileData);//where null is the filename
             StopWordList st=new StopWordList("Stop.txt",stopWords);
            LinkedList<String[]> dataAfterstopOperation= st.checkStopWords(dataAfterTokinization2);
            for (int i = 0; i < dataAfterstopOperation.size(); i++) {
                for (int j = 0; j < dataAfterstopOperation.get(i).length; j++) {
                    txrdupld.append(" "+dataAfterstopOperation.get(i)[j]);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StartTokenizeTwo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rdupActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        shupload.setEnabled(true);
    }//GEN-LAST:event_uploadActionPerformed

    private void shuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shuploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton rdup;
    private javax.swing.JTextArea resultstop;
    private javax.swing.JTextArea sentstop;
    private javax.swing.JTextField shupload;
    private javax.swing.JButton stop;
    private javax.swing.JTextArea txrdupld;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
